# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

beta_ridge_C <- function(X, Y, lambda_beta) {
    .Call(`_StrippedGraphicalVAR_beta_ridge_C`, X, Y, lambda_beta)
}

Beta_C <- function(kappa, beta, X, Y, lambda_beta, lambda_beta_mat, convergence, maxit) {
    .Call(`_StrippedGraphicalVAR_Beta_C`, kappa, beta, X, Y, lambda_beta, lambda_beta_mat, convergence, maxit)
}

VAR_logLik_C <- function(X, Y, kappa, beta) {
    .Call(`_StrippedGraphicalVAR_VAR_logLik_C`, X, Y, kappa, beta)
}

LogLik_and_BIC <- function(X, Y, estimates) {
    .Call(`_StrippedGraphicalVAR_LogLik_and_BIC`, X, Y, estimates)
}

inner_loop <- function(S, W, X, WXj, Wd, n, rho, thrLasso) {
    .Call(`_StrippedGraphicalVAR_inner_loop`, S, W, X, WXj, Wd, n, rho, thrLasso)
}

